name: simplenote
title: Simplenote
summary: The simplest way to keep notes.
description: |
 Simplenote is an easy way to keep notes, lists, ideas and more. Your
 notes stay in sync with all of your devices for free.
version: '2.21.0'
license: MIT
website: https://simplenote.com/
source-code: https://github.com/Automattic/simplenote-electron/
contact: https://github.com/snapcrafters/simplenote
issues: https://github.com/snapcrafters/simplenote/issues
icon: snap/gui/simplenote.png

base: core24
compression: lzo
grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

parts:
  simplenote:
    source: 
      - on amd64: https://github.com/Automattic/simplenote-electron/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/Simplenote-linux-${SNAPCRAFT_PROJECT_VERSION}-x64.tar.gz
    plugin: dump
    prime:
      - -chrome-sandbox
      - -LICENSE*

plugs:
  shmem:
    interface: shared-memory
    private: true

apps:
  simplenote:
    command: simplenote --no-sandbox
    desktop: meta/gui/simplenote.desktop
    extensions: [ gnome ]
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources
      TMPDIR: $XDG_RUNTIME_DIR
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - cups-control
      - home
      - network
      - removable-media
      - unity7
